<!DOCTYPE corpora [
<!ELEMENT corpora (yes,no+)>
<!ATTLIST no right CDATA "">
<!ELEMENT yes (#PCDATA)>
<!ELEMENT no (%right)>
]>
<corpora>
    <yes>סליחוה נמנהג ק׳׳ק ספרדים יצ״</yes>

    <no right="ו">ו־</no>

    <yes> ---*0^0־--- נדפס פה ביינה שנת כת</yes>

    <no right="ר׳׳">ר</no>
    <yes>ה על ידי הצעיר יוסף יצהק אלשיך ה׳׳י ואשהו רבקה מנ״ה לזנרון אבדהם יצחק אלשיך ע</yes>
    <no right="׳׳">־</no>
    <yes>ה ויצחק יטקב אליהו ט</yes>
    <no right="׳׳">־</no>
    <yes> ה: סליחוה קון לאדינו</yes>

    <no right="ס">ק</no>
    <yes>י אי</yes>

    <no right="ס">ק</no>
    <yes>טאמפארון לה פרימה </yes>
    <no right="בˇ">ב</no>
    <yes>י</yes>

    <no right="ז">־</no>
    <yes> אין </yes>

    <no right="בˇ">ב</no>
    <yes>יינה אין אנייו 5625 אי</yes>

    <no right="טס">קנו</no>
    <yes>י לי</yes>

    <no right="בˇ">ב</no>
    <yes>רו איס אייאדו </yes>

    <no right="ס">ק</no>
    <yes>ולו אונדי</yes>

    <no right="ס">ק</no>
    <yes>י׳ יו</yes>

    <no right="ס">ק</no>
    <yes>ף יצחק אלשיך ה״י אין </yes>

    <no right="בˇ">ב</no>
    <yes>יינה. אי איל ריקא</yes>

    <no right="בˇ">ב</no>
    <yes>דו פו</yes>

    <no right="ר">ל</no>
    <yes> אייו אי</yes>

    <no right="ס">ק</no>
    <yes> אין</yes>

    <no right="פˇ">פ</no>
    <yes>א</yes>

    <no right="בˇ">ב</no>
    <yes>ור די גמילוה חסדים אמרי האזינה ה׳ בינה הגיגי הקשיבה לקול שוטי מלני ואלהי ני אליך אהפלל</yes>

    <no right=":">ן</no>

    <yes> יזנור ואל ישנך מלברך נרנוה התורה </yes>

    <no right="כד">בר</no>
    <yes>י לומר סליחוה נרטה רבינו בטל הטורים </yes>

    <no right="ו׳׳">ר</no>
    <yes>ל שפסק שלא יקרא פסו</yes>

    <no right="ק">ס</no>
    <yes>י</yes>

    <no right="ם">ש</no>
    <yes> קורם ברנה ההורה אף טל פי שאומרים דרך החנונים. ואשר בא בסוד ה׳ י</yes>

    <no right="כו">מ</no>
    <yes>ין לברך בטה ההיא נל סדר הברנוה יטן שאינו ראוי להפסיק </yes>
    <no right="ב">נ</no>
    <yes>י</yes>


    <no right="נ">ג</no>
    <yes>יהם כי קשר ויהוד אחד לכולם מההלה נטילה ידים טד ברנוה ההורה ננודט ליודטי חן גם צריך ליזהר לומר נל סדר הקון חצוה נפי מה שהובא בספר שטרי צ</yes>

    <no right="ןיו">ק</no>
    <yes> ני הוא טיקר גדול לבנוה ולההאבל טל חרבן ביה מקדשינו וישב יחף טל הארץ ויהחיל טל נהרוה בבל ונו׳ ננהוב שם: מיס די</yes>

    <no right="גˇ">ג</no>
    <yes>א</yes>

    <no right="ס">ק</no>
    <yes> אי</yes>

    <no right="ס">ק</no>
    <yes>ק</yes>
    <no right="וגˇ">גל</no>
    <yes>ה ה׳ אינ</yes>
    <no right="טיי">נרי</no>
    <yes>נדי מי א</yes>

    <no right="בˇ">ב</no>
    <yes>לה איסקו</yes>

    <no right="גˇ">ג</no>
    <yes>ה אה </yes>

    <no right="ב">נ</no>
    <yes>וס </yes>

    <no right="ד">ר</no>
    <yes>י מי איסקלאמא</yes>

    <no right="ס">ק</no>
    <yes>ייו</yes>

    <no right="ן">;</no>
    <yes> מי </yes>

    <no right="רי">מ</no>
    <yes>י אי מי דייו קי א</yes>

    <no right="ט">בר</no>
    <yes>י אגו אוראסייון: מימ</yes>

    <no right="ב">נ</no>
    <yes>רארה אי </yes>

    <no right="נו">מ</no>
    <yes>ן אול</yes>
    <no right="בˇ">ב</no>
    <yes>ידארה די בינ</yes>
    <no right="דיזי">ריד</no>
    <yes>ר לאס בינ</yes>
    <no right="ד">ל־</no>
    <yes>יסײוניס די לה ליי פארה דיזיר סליחוה סי</yes>
    <no right="ג">ב</no>
    <yes>ון ס</yes>
    <no right="בˇ">ב</no>
    <yes>רה די רב</yes>
    <no right="ינ">ט</no>
    <yes>ו בעל ה</yes>
    <no right="ט">נו</no>
    <yes>ורי</yes>
    <no right="ם">ס</no>
    <yes>ז״ל איל קואל קורטו פור</yes>
    <no right="ר">ד</no>
    <yes>ין די </yes>
    <no right="נו">מ</no>
    <yes>ן די</yes>
    <no right="זי">ד</no>
    <yes>ר אי מילדאר פסוקים אנ</yes>
    <no right="ט">נו</no>
    <yes>יס די בינדי</yes>
    <no right="ס">ק</no>
    <yes>ײוניס די לה ליי אא</yes>
    <no right="ןו">ץ</no>
    <yes> קי לוס דיזין פור רוגא</yes>
    <no right="ט">נו</no>
    <yes>י</yes>
    <no right="בˇ">ב</no>
    <yes>ה: אי איל קי </yes>
    <no right="בˇ">ב</no>
    <yes>ינו אין סיקרי</yes>
    <no right="ט">נו</no>
    <yes>ו די ה׳ </yes>
    <no right="טי">נר</no>
    <yes>נגה לה אינ</yes>
    <no right="ט">נו</no>
    <yes>יסייון די בינדיזיר אין איס</yes>
    <no right="ט">נו</no>
    <yes>ה אורה טודו איל אורד</yes>
    <no right="ין">ץ</no>
    <yes> די בינדיסייוניס סײנדו קי נין איס פיר-טיניסיין פור איס</yes>
    <no right="ט">נו</no>
    <yes>א</yes>
    <no right="זˇ">ז</no>
    <yes>אר אינ</yes>
    <no right="ט">נו</no>
    <yes>רי אייאס פו</yes>
    <no right="ר">נ</no>
    <yes>קי א</yes>
    <no right="ט">נו</no>
    <yes>א</yes>
    <no right="מי">נר</no>
    <yes>ינ</yes>
    <no right="ט">נו</no>
    <yes>ו אי אאונאמיינ</yes>
    <no>נו</no>
    ו אה
    <no>נװ</no>
    דאס די פריסיפײו די ברנה די
    <no>ננר</no>
    ל
    <no>ס</no>
    די מאניס אסט
    <no>־</no>
    ה בי נ<no>ל</no>
    יסייוניס די לה ליי סי
    <no>מ</no>
    ן סא
    <no>ב</no>
    ידו:
    <no>נו</no>
    אמביין איס די אקא
    <no>ב</no>
    ידארסי פור דיזיר
    <no>מ</no>
    יקון חצו
    <no>ס</no>
    סיינדו טיקר גרא
     נדי פור ייוראר אי אלימו
     נייאר סו
    <no>ב</no>
    רי דיס
    <no>נו</no>
    <no>מ</no>
    איסײון די קאזה די נואיס־טרה סא
     נ<no>נר</no>
    דאד אי סי אסי
     נ<no>נר</no>
    דיסקאלסו סו
    <no>ב</no>
    רי לה
    <no>נו</no>
    יי
     נ<no>ס</no>
    אי אימפי
    <no>נך</no>טל נהרו
    <no>ס</no>
    בבל סיגון איסקרי
    <no>נו</no>
    ו אין לי
    <no>דנ</no>
    ז
שטרי ציון;	1
1
לאדינו די בקשוה
דורמידו נוןטי אדורמי
    <no>ק</no>
    קא
    <no>ק</no>
לאדינו
2טל פור מי פאלאסייו ייורארי די דייאה אי די
    <no>פ</no>
    וגי. אי פור אירמחורה די ציון סיב׳דאד לה אלאב׳אדה: בני יורו דיקו
    <no>פ</no>
    <no>נר</no>
    <no>פ</no>
    ו פור
    <no>לײ</no>
    ס
    <no>נו</no>
    <no>מ</no>
    ײ
    <no>ק</no>
    י
    <no>ױ</no>
    ן די דוס ב׳יזיס.טיירה די קוב׳דיסייאה קוב׳דיסײאה די ירושלי
    <no>ס</no>
    . אי פור טו פואיב׳לו קי א
    <no>פ</no>
    דו
    <no>נ</no>
    ׳ו איניל קאטיב׳ירייו: ביה קאזה די מי אירמוזורה פ
    <no>ח</no>
    ו אי
     נימיגו פור דיסולאדורה. מי איזו איסטאר אין מאנוס די
    <no>פ</no>
    ביוה אי די שמה. פור איסטו ייורארי דיקו
    <no>פ</no>טי
    <no>פ</no>
    ו קון בוז די אלגואייאה: ספרי אי
    <no>פ</no>
    די
    <no>ג</no>
    ה ליי קי
    <no>צ</no>
    ואי איסביב׳לאדהטו אירמוזורה. קאייו טו קורונה דיל דייאה קי
    <no>פ</no>
    ואי דיסטר
    <no>ר</no>
    ידהטו קאזה. אי אלסה אי
    <no>פ</no>
    די
    <no>ג</no>
    ה פור אהליבה אי אהלה: חזקו אי
    <no>פ</no>
    <no>פ</no>
    ור
    <no>נו</no>
    יסי
    <no>מ</no>
    ׳וס מי פואיב׳לו די פריסה פ׳ראגוארי
    <no>ב</no>
    ואיסטרו פ
    <no>^</no>
    אסייו די
    <no>ב</no>
    י
    <no>פ</no>
    גאנסה מי
    <no>ב</no>
    יסטירי אי אריטורנאר אה
    <no>ב</no>
    ואיסטרה טור
    <no>פ</no>
    א
    <no>פ</no>
    סה. אינ
    <no>נמ־</no>
    י מי פאלאסייו מורארי קומו אי
    <no>פ</no>
    יל פריסיפייו. קי די ציון סארלה ליי אי לואור: קומו קי דיזי איל פ
    <no>ק</no>
    וק קי די ציון סארלה ליי אי פאלא
    <no>ב</no>
    רה די ה׳ די ירושלים:
קאנטאר די לוס גראדוס אין טורנאר ה׳ אטור
    <no>פ</no>
    א
    <no>פ</no>
    סה די ציון פ׳ואימוס
קומו סונייא
     נטיס
    <no>נ</no>
    איסטונסיס סירה אינ
    <no>3</no>
    ידו די ריזו
    <no>פ</no>
    ואיסטרה בוקה אי נואיסטרה לואי
    <no>פ</no>
    גה קא
     נטאר איסטו
     נסיס דיראן אי
     נלאס ג׳ינטיס אי
     נגראנדי
    <no>ש</no>
    ײו ה׳ פור אזיר קון איסטוס אי
    <no>פ</no>
    גרא
     נדי
    <no>נך</no>
    <no>ױ</no>
    ה' פור א
    <no>ד</no>
    ר ק
    <no>ר</no>
    ן  נ<no>י</no>
    ס פואימוס חליגריס:טור
    <no>פ</no>
    ה ה׳ אה נואיסטרהטור
    <no>פ</no>
    א
    <no>פ</no>
    סה קומו פילאג
    <no>י</no>
    ס אין לה סיקורה: לוס סימבראנטיס קון לאגרימה קון
    <no>ק</no>
    אנטאר
    <no>ק</no>
    יגאראן: א
    <no>פ</no>
    דאר אנדארה אי ייוראר ייב׳אן סונטראימ
    <no>״</no>
    <no>פ</no>טו די סימ
    <no>ץ</no>
    ב׳יניר
    <no>ב</no>
    ירנה ק
    <no>י</no>
    ן קא
    <no>פט</no>
    אר יי
    <no>ב</no>
    א
    <no>[</no>
    ס
    <no>י</no>
    ס גאב׳ילייאס:
הפלה אוראסייון אה דוד א
    <no>ר</no>
    י ה
    <no>'</no>
    <no>ג</no>
    וסטידאד איסקו
    <no>ג</no>
    ה מי קלאמור אי
    <no>ק</no>
    קו
    <no>ג</no>
    ה מי אויאסייון סין לא
    <no>נ</no>
    ייוס די אינגא
    <no>פ</no>
    ייו: דילאנטרי דיטי מי
    <no>ג</no>
    ואיסייו סאלגה
    <no>נװ</no>
    ס קאטא
    <no>ײ</no>
    ס
    <no>ב</no>
    יראן ד
    <no>ר</no>
    י
    <no>ג</no>
    ידאדיס: פרי
    <no>נ</no>
    אסטיס מי קוראסון
    <no>ב</no>
    י
    <no>ז</no>
    יטא
    <no>ה</no>
    טיס די
    <no>מג</no>
    י איזמיראז
    <no>פר</no>
    זמי נון אלייאטיס לוקי פי
    <no>פ</no>
    סי
    <no>פ</no>
    ון פאסו מי די
    <no>ג</no>
    ו: אה אוב׳ראס די אומ
    <no>נ</no>
    רי אין אב׳לה די טוס לא
    <no>נ</no>
    ייוס ייו גואדרי קאמי
    <no>ט</no>
    ס די פורטילייאדור: אסו
    <no>פ</no>
    רי מיס פאטאדאס קון טוס סי
    <no>פ</no>
    די
    <no>ײ</no>
    ס
    <no>פ</no>
    ון סי ריספ
    <no>י</no>
    ייגאן מיס פייס: ייוטי ייאמי קי מי ריספו
    <no>פ</no>
    דאס דייו אקוסטה טו פריזינסייאה אה מי אויי מי די
    <no>ג</no>
    ה: אז אפארטאר ט
    <no>י</no>
    ס מירסידיס סאל
    <no>ב</no>
    אן אבריגא
    <no>מו</no>
    יס די איסקואי
    <no>פ</no>
    טרה אליב׳א
    <no>פ</no>
    טא
    <no>פ</no>
    טיס אי
    <no>פ</no>
    טו דירי
    <no>ג</no>
    ה: גואדראמי קומו
    <no>פ</no>
    יגרורה די
    <no>פ</no>
    י
    <no>פ</no>
    ייטה די או
    <no>ז</no>
    ו אין סולומברה די טו שני
    <no>פ</no>
    ה מי אינקו
    <no>ג</no>
    ראס: פארה מודרי מאליס קי מי פרייארון מיס אי
    <no>פ</no>
    ימי
    <no>מ</no>
    ס קון
    <no>ב</no>
    ילו
    <no>פ</no>
    טאד רודייאן סו
    <no>נ</no>
    רי מי: סוס סי
    <no>נ</no>
    ׳וס סירא
    <no>מ</no>
    ן סוס
    <no>גי</no>
    קאס א
    <no>ב</no>
    לארון קון אלטיגואיזה: מואיסטראס פאטאדאס אגורה מוס ארודייארון סוס או
    <no>זי</no>
    ס פו
    <no>פ</no>
    ין פור אקוסטאר אין לה טיירה: סי סימי
    <no>ז</no>
    א
    <no>פ</no>
    סה קומו ליאון קי קוב׳דוסייאה פור ארי
    <no>ב</no>
    אטאר אי קומו קאדילייו איסטאן אין אינקו
    <no>ב</no>
    יירטאק: אלי
    <no>ב</no>
    אנטה ה
    <no>'</no>
    אקו
    <no>פ</no>
    אנטה
לאדינו
2טל פור מי פאלא
    <no>ק</no>
    ײו ײורארי די דײאה אי די נו
    <no>גי</no>
    י אי
    <no>ס</no>
    ור אירמחורה די ליון
    <no>ק</no>
    יב׳דאד לה אלאב׳אדה: נני יו
    <no>ל</no>
    ו דיקונטינו פור די
    <no>ק</no>
    טרוײ
    <no>ק</no>
    ײון די דוס ב׳יזי
    <no>ק</no>
    . טיי
    <no>ל</no>
    ה די קוב׳דיסייאה קוב׳די
    <no>ק</no>
    ייאה די ירושלים. אי פור טו פואיב׳לו קי אנדוב׳ו אי
    <no>פ</no>
    יל קאטיב׳ירייו: ביה קאזה די מי אירמ
    <no>ח</no>
    ורה פוז
    <no>ר</no>
    אינימיגו פור דיסולאדורה. מי איזו אי
    <no>ק</no>
    טאר אין מא
    <no>פ</no>
    ו
    <no>ק</no>
    די
    <no>פ</no>
    ביוה אי די שמה. פו
    <no>ל</no>
    איסטו ייורארי דיקונטינו קון בוז די אלגואייאה: ספדי אינדי
    <no>ג</no>
    ה ליי קי
    <no>צי</no>
    אי אי
    <no>הנ</no>
    יב׳לא
    <no>ו</no>
    ה טו אירמוזורה. קאייו טו קורונה דיל דייאה קי
    <no>$</no>
    ואי די
    <no>ק</no>
    ט
    <no>ל</no>
    ויידה טו קאזה. אי אל
    <no>ק</no>
    ה אינדי
    <no>ג</no>
    ה פור אהליבה אי אהלה: חוקו אינ
    <no>פ</no>
    ורטי
    <no>ק</no>
    ידב׳ו
    <no>ק</no>
    מי פואיב׳לו די פרי
    <no>ק</no>
    ה פ׳ראגוארי
    <no>ב</no>
    ואי
    <no>ק</no>
    טרו פ
    <no>^</no>
    א
    <no>ק</no>
    ייו די
    <no>ב</no>
    ינגאנ
    <no>ק</no>
    ה מי בי
    <no>ק</no>
    טירי אי ארי טורנאר אה
    <no>ב</no>
    ואי
    <no>ק</no>
    טרה טורנאנ
    <no>ק</no>
    ה. אינטרי מי פאלאקייו מו
    <no>ל</no>
    ארי קומו איניל פרי
    <no>ק</no>
    יפייו. קי די ציון
    <no>ק</no>
    ארלה ליי אי לואור: קומו קי דיזי איל פקוק קי די ציון קאללה ליי אי פאלאברה די ה׳ די ירושלים:
שיך קאנטאר די לוק גראדוק אץ טורפאר ה׳ אטולנאנקה די ציון פ׳ואימוק קומו קופייאנטיק: איקטונקיק קירה אינ^ידו די ריזו פואיקטרה בוקה אי נואיקטרה לואינגה קאפטאר מיקטונקיק דיראן אינלאק ג׳ינטיק אינגראנדיקייו ה׳ פוראזיר קון אי&טוס איננראנדיסייו ה' פור אזיר קון נוק פואימוק אליגריק: טורנה ה׳ אה נואיקטרה טורנאנקה קומו פילאגוק אין לה קיקורה: לוק קימבראנטיק קון לאגרימה קון קאנטאר קיגאראן: אפדאר אנדארה אי ייוראר ייב׳אן קונטראימיינטו די קימין ב׳יניר בירנה קון קאנטאר ייבאן קוק גאב׳ילייאק:
הפלה אוראקייון אה דוד אויי ה' נוקטידאד איקקוגה מי קלאמור איקקונה מי אוראקייון קין לאבייוק די אינגאנייו: דילאנטרי די טי מי נואיקייו קאלגה טוק קאטאריק ביראן דיריגידאדיק: פריבאקטיק מי קוראקון ביזיטאקטיק דינוגי איזמיראזטיזמי פון אלייאטיק לוקיפינקי נון פאקו מי דיגו: אה אוב׳ראק די אומברי אין אב׳לה די טוק לאבייוק ייו גואדרי קאמינוק די פורטילייאדור: אקו5רי מיק פאטאדאק קון טוק קינדירוק פון קי ריק£וייגאן מיק פייק: ייו טי ייאמי קי מי ריקפונדאק דייו אקוקטה טו פריזיפק״אה אה מי אויי מי דיגה: אז אפארטאר טוק מירקידיק קאלבאן אבריגאנטיק די איקקואינטרה אליב׳אנטאנטיק אינטו דיריגה: גואדראמי קומו ניגרורה די נינייטה די אוזו אין קולומברה די טו שנינה מי אינקו3ראק: פארה מודרי מאלוק קי מי פרייארון מיק אינימיגוק קון בילונטאד רודייאן קוברי מי: קוק קיב׳וק קירארון קוק בוקאק אבלארון קון אלטימאיזה: מואיקטראק פאטאדאק אגורה מוק ארודייארון קוק או?וק פונין פור אקוקטאר אין לה טיירה: קו קימיזאנקה קומו ליאון קי קוב׳דוקייאה פור אריבאטאר אי קומו קאדילייו איקטאן אין אינקוביייטאק: אליבאנטה ה' אקונאנטה
לאדינו
3
סוס 5אסיס קיבלאפטאלו איסקאפה מי אלמה די מאלי קי איס נוו איספאדה: די באלופיס קי סון טו ייאגה ה׳ די בארופיק די מיפדו סל פאלטי אין לאס בידאס אי מוס איסקופדידיזוס איפגילאס סוס בייפטליס ארטאלסיאן די איזיס אי דיישאלאן סו לומאזיזה אה סוס גיקינייס: ייי קון גוסטידאד בילי ? טוס פאסיס אלטאלמיאי אין דיספילטאל מו אסימיזאנסה: לךןף אה דוד סאלמר ניין א3יפטולאדו פידלונאדו די ליבילייו קוביילטו די פיקאדו: ביין אביפטולאדו אומנלי קי נון קונטה ה' אה איל דיליטו אי נון איפסו בילופטאד אמר: קי סי מי אקאלייו סי אינניזיסין מיס גיאיסיס קונמי בלאמידו טרדו איל דיאה: קי דייאה אי פוגי סי אפיזגה סיברי מי טו ייאגח פואי מלאסטופאדה אמי פליסקול אין סיקולאס די איפבילאפו סיינפלי: מי פיקאדו טי אלי סאביל אי מי דיליטו מן קובלי די!שי אטולגארי נןובלי מיס לינילייוק אה ה' אי טו פידלופאסמיס דיליטו די מי פיקאדו סייפפלי: פול איקטו אלה אולאסייון טודו בואיפו אטי אה אולה די אלייאר דיסיילטו אה אלאבדון די אמאס מומ׳אס אאיל נון סי אלייגאלאן: טו איפקוביילטה אה מי די אפגוסטייאדול מי גואדלאלאס קאנטאליס די איסקאפאמייפטו מי לודייאלאס ניימפלי: אזילטיאי אינטיפדיל אי אמוקטלאל טיאי אין קאלירה קי אנדאלאס אסיפייאלי סונלי טי לוקי בידו מי אוזו: פון סיאדיש קומו קאבאייו קומו מולה סין איפנרפדיר קון פליפו אי קאגליסטו פול סילאל סו בוקה פול פון אלייגאלסי אה טי: מופגאס דולילינן אה איל מאלו אי אה איל איפ$יאחייאן אין ה, מילסיד לו אלודייאלה: אליגלמדנוס . קון ה׳ אי אגוזאדנוס מסמוס אי קאפטאד דיליגילוס די קול׳:
אאיל איס^ולסאן סאלמר אה דוד: אין ניפיל אה איל נהן איל פלוציטה קומו ביפו אה בה ש3ט: אגלאסייאמי דייו קומו טו מילסיד קומו מופגידומבלי די מוס פייאדאדיס אלימאטה מיס לי^ילייוס: מופגו לאבאמי די מידיליטו אי די מיפיקאדו אלימפייאמי: קי מיס לטילייוק יױ סי אי מי פיקאדו איסקואיפטלה מי דיקופטיפו: אמי אטו סולאס פיקי אי לו מ^יר אין טוס קאטאליס איזי פולקי טי מסטיציקיס איפטו אבלאל מיליסקאק איפטו מזגאל: איג קון דיליטו פואי קלייאדו אי קון פיקאדו סי איסקאלייפטו דימי מי מאדלי: איג בידלאר איפנילופטאזנרס איפליס ליפייופיס אי איפסילאדו סיפסייאה מי אלאס סאניל: אלימפײאלמיאסקוןאוליגאפואיאלימפײאלמיאילאבאלמיאס אי מאס קי פייני מי איפבלאפקיסילי: אזילמיאס אוייל נחו אי.גזיגרייה אגוזאלסיאן גואיסיס קימאזאסמיס: איפקובלי טוס ^אסיסדי מיס פיקאדוסאי מודוס מיס דילימוס אלימאטה: קול' ליפפייוקלייאה אמי דייו אי איספילינװ קופפואיסטו ליפוב׳ה איפטלי מי: פון מי איגיס דילאנטלי דיטי אי איספיליטו די טו סאפטידאד נוןטומיס דמי: אז טולפאל אמי גוזו די טוס^נאסײוןאיקוןאיספיליטושאריצי
לאד״ינו
3
סוס צאסיס קיבראפטאלו איסקאפה מי אלמה די מאלו קי איס טו איספאדה: די בארוניס קי סון טו ייאגה ה׳ די בארוניס די מונרו סו פארנוי אין לאס בידאס אי טוס איסקונדידיזיס איפגילאס סוס ביינטריס ארטאלסיאן די איזיס אי די׳שאראן סו רומאזיזה אה סיס גיקיטיס: ייו קין גוסטידאר בירי טוס פאסיס ארטארמיאי אין דיספירטאר טו אסימיזאפסה:
לףןף אה דוד סאלמו ביין אבינטוראדו פידרונאדו די ריבילייו קו3ײרטו די פיקאדו: ביין אבינטוראדו אומברי קי נון קונטה ה' אה איל דיליטו אי נון אינסו בילונטאד ארטי: קי סי מי אקאלייו סי אינבאיסץ מיס גואיסיס קונמי בראמידו טודו איל דייאה: קי דייאה אי נדגי סי אפיזגה סוברי מי טו ייאגה צואי טלאסטונאדה אמי פריסקור אין סיקויאס די אינב־יאנו סיינפרי: מי פיקארו טי אלי סאביר אי מי דיליטו מן קוברי די&י אטורגארי נןוברי מיס ריבילייונן אה ה' אי טו פידרונאסטיס דיליטו די מי פיקאדו סיינפרי: פור איסטו ארה אוראסייון טורו בואינו אטי אה אורה די אלייאר דיסיירטו אה אראבדון די אגראס מופג׳אס אאיל נון סי אלייגאראן: טו אינקוביירטה אה מי די אנגוסטייאדור מי נואדראראס קאנטאליס די איסקאפאמײננװ מי רודייאיאס ניימפרי: אדרטיאי אינטינדיל אי אמוסנוראר טיאי אין קארירה קי אנדאלאס אסינייארי סוברי טי לוקי בידו מי חוזו: פון סיאדיש קומו קאבאײו קומו מולה סין אינטינדיר קון פרינו אי קאנייסטו פור סיראר סו בוקה פור פון אלייגאלסי אה טי: מופגאס דולוליס אה איל מאלו אי אה איל אינפיאוזייאן אין ה' מירסיד לו ארודייארה: אטגלהדבוס קון ה7 אי אגוזאדנונן גיסנװס אי קאפטאד דיריגילוס די קור׳: ל^צח אאיל איס^ויסאן סאלמו אה דוד: אין ביניר אה איל נהן איל פרופיטה קומו בינו אה 3מ שבט: אגראסייאמי דייו קומו טו מירסיד קומו מוננירומברי די טוס פייאדאדיס ארימאטה מיס רי5ילייוס: מונגו לאבאמי די מידיליטו אי די מיפיקאדו אלימפייאמי: קי מיס ריניל״יס ייו סי אי מי פיקאדו איסקואינטרה מי דיקונטיפו: אטי אטו סילאס פיקי אי לו מג1ו אין טוס קאטאריס איזי פורקי טי גוסטי^יקיס אינטו אבלאר מיריסקאק אינטו גוזגאר: איג קון דיליטו £ואי קרייארו אי קון פיקאדו סי איסקאליינטו דימי מי מאדרי: איג בידראד אינבילונטאזטיס אינלוסרינייוניסאי איפסיראדו סיפסײאה מי אלאס סאביר: אלימפייארמיאס קון אוריגאנואיאלימפייארמיאילאבארמיאס אי מאס קי נייבי מי אינבלאנקיסירי: אזירמיאס אוייר גוזו אי:זיגרייה אגוזארסיאן גיאיסיס קי מאזאסטיס: אינקוברי טוס פאסיס די מיס פיקאהס אי פוריס מיס דיליטוס ארימאטה: קור' לינפייוקרייאה אמי דייו אי איספיריטו קונפואיסטו רינוב׳ה אינטרי מי: נון מי איגיס דילאנטרי דיטי אי איספיריטו די טו סאפטידאד מןטומיס דימי: אזטורנאראמיגוזו די טוס^באסייוןאיקוןאיספיריטושאריצי
לאױנו
3
היס פאסיס קיבלאנטאלו איקקאפה מי אלמה די מאלו קי איס טו איקפארה: די באלוניס קי קון טו ײאגה ה׳ די באמפיק די מונדו קו פארנױ אין לאס בידאס אי נװס איסקונדידיזונן אינגיראק סיס בײנטליס ארטאלסיאן רי איזוק אי די&אראן קו לומאזיזה אה קונן גיקיטיס: יױ קון מסטידאר בירי נװס ^אשיס ארטאמױאי אין דינןפילטאר טו אקימיזאנקה:
לףףך אה דוד קאלמו בײן אביפטולאדו פידרונאדו די ריבילײו קובײרטו די פיקאדו: ביץ אנינטוראדו אומברי קי נון קופטה ה׳ אה איל דיליטו אי פון אינסו בילונטאד אלנר' קי סי מל אקאל״ו קי איפני^יסץ מינן גואיסיס קונמי נלאמידו טודו איל דײיאה: קי דײאה אי טגי סי אפיזגה סיברי מי טו ײאגה פואי טראקטונארה אמי פלינןקור אץ סיקמ־אס די איננ־לאנו סײנפרי: מי פיקאדו טי ארי סאניר אי מי דיליטו נון קוברי דישי אנװלגאלי סונרי מיס ריבילײויס אה ה1 אי טו פידרונאסטיק דיליטו די מי פיקאדו סײנפלי: פור איסטו ארה אילאסײון טורו בואינו אטי אה אורה די אלײאר דיקײרטו אה אראגדון די אגואק מונג׳אנן אאיל נין סי אלײגאראן: טו אינקונײלטה אה מי די אנגוסנױיאדול מי גואדראראס קאנטאריק די איסקאפאמײנטו מי לודײאלאס נײמפלײ אזירנראי איננױנריל אי אמוקניראר טיאי אין קארירה קי אנדאלאנן אקינײאלי קוברי טי לוקי בידו מי אוזו: נדן סיאדיש קומו קאבאײו קרמי מולה קין איננױנדיר קון פליפו אי קאבריקטו פול סילאל סו בוקה פרר נון אלײגאלסי אה טי: מונגאס דולוריק אה איל מאלו אי אה איל אינפיאוזײאן אין ה׳ מילקיר לו ארודײארה: אלינרחדנוס קון ה׳ אי אגוזאדבוק גיהטוס אי קאנטאד דיליגירוס די קרר׳: ל^צה אאיל איספולסאן קאלמו אה רור: אץ ביניל אה איל פהן איל פרופיטה קומו בינו אה נה שבט: אגראסײאמי דיױ קומו טו מילסיר קומו מונגידומנלי די טינן פײאלאיײס ארימאטה מיס ריגילײוס: מונגולאבאמידי מידיליטו אי די מיפיקאדו אלימפײאמי: קימיק רינילײוס יױ סי אי מי פיקארו איסקואטטרה מי דקוננױנו: אנױ אנרו סילאס פיקי אילומגגו אץ טיס קאטאײס איזי פולקי טי גוסטיפיקיס איפטו אבלאר מיריקקאק איפטו גחגאל: איג קון דיליטו 5ואיקלײאדו אי קון פיקאדו סי איסקאלײנטו דימי מי מאדרי: איג בידראד אינבילונטאזטיס אינליס יינײוניס אי אינקיראח־ קינקײאה מי אלאס סאביר: אלימפײאלמיאס קון אוליגאנו אי אלימפײאמראי לאבאלמיאס אי מאנן קי נ״בי מי אינבלאפקיקירײ אזימראס אױיל גחו אי *זיגרייה אגחאלסיאן טאיסוס קימאזאהמיס: אינקובױ טוק פאסיסדי מיס פיקאמסאי טוריס מיס רילינויס אלימאטה: קור' ליפפײוקרײאה אמי דײו אי איספיײטו קונפואיסטו יינולהאיפנמ־ימי: מן מי איגיהדילאנטײריטיאיאיספיליטוריטו סאנטידאר נוןטומיס לימי: אזטומאראמיגחו די טוס^באנןיױןאיקרן איספיריטושאריפי
לאדינו
4
מי אקופלילאק: אפביזאלי אליבילייאמליס מוס קאלילאק אי פיקאדוריס אטי טורנאראן: איסקאפאמי די אומיזיייס דייו דייו די מי קאלנאסייון קאנטארה מי לואינגהטו נוסטידאד: ה׳ מיק לאבייוק אבלילאק אי מי בוקה דיטקייאלה טו לואול: קי נון איפנילופטאק קאקלי$יקייו ני דאדי3ה אלקאנןײון נון איפבילופטאס: קאקליפייוק די איל דייו איספיליטו קיבלאדו קול׳ קיבלאדו אי מאזאה דייו פון מיטספלייאה: אבוניגואה קופטו בילופטאד אה ציון פלאמאלאק קילקאק די ילושליס: איקטופקיס איפבילופטאלאק קאקליפיקייוק די גלסטידאד אלקאסייון אי קימאדו איקטונסיס אלסאלאן קובלי טו אלה טולוס: ל^צח אה איל איק5ורקאן קאלמו אה דוד קאפטאל: אטי קאלייאדורה לואול דיאיל דייו אין ציון אי אטי איס פאגאדה פלומיטה: אוליץ אולאסייון אסטה טי טודה קלייאדולה בילפאן: פאלאבלאק די דיליטלס סי מאייומאלון די מי מואיסטללס ליביליילס טי ליס פידלונאלאק: ביין א3ינטולאדו אל קי איסקחיס אי אלייגאק קי מולי אין טוס קולטיס אלטאלמוסאימוס קון ביין די טו קאזה סאפטו די טו פאלאסייו: טימו* לידאדיס קון גלסטידאד מס ריספופדיראק דייו די מיאיסטרה קאלבאקייון פיאוזייאה די טודוקקאבוק די טיילה אי מאל די לי&אפוק: קונפופיין מונטיס קון סו פואירקה קיפיידו קון באלאגאפייאה: אזיין אקידאל סופידוק די מאליס סופידוס די סוס ארלאס אי לואידו די גיפטייוק: אי טימיילון מולאדוליס די קאביס די מלס קיפייאליס קאלידאק די מאפייאפה אי טאדלי אזיק קאנטאל: ביזיטאקטיק לה טיילה אי אבט׳לאסטיזלה מופגו לה אזינן איפליקיסיל פילאגו די איל דייו ייפו די אגואק קופפופי סו סיבילה קי אפקי לה קופפוניס: סיס :שולקוק אז אלטאל אז דיסיפדילקון סלס באלייאדוק קון גוטאק לה דיזלייק קו אילמוייו בינדיזילאס: איפקולופאסטיס איל אפייו די טו ביין אי טוק קיפדילוק גוטייאלאן נ׳יסייו. גונריאלאן מולאדאק די דיזיילטו אי גוזו די קלאיסטאק קיפיילאן: נ׳יסטיילון פלאדלס לאס אוב׳יזאק אי ב׳אלייק איפבולב׳ילאן קיב׳ילה אאוב׳לאלאן טאמביין קאפטאלאן:
אה איל איקפולקאן אה אי׳ווק די קלח קאלמו: אינב׳ילופטאקטיק ה' טו טיילה טולפאקטיק קאטיב׳ילייו די יטקב: פידלופאקטיק דיליטו די טו פואיב׳לו קוב׳ליקטיק טודוס קוק פיקאדוק קיימפלי: אפאפייאקטיק טודה טו סאפייאה איזיסטיס טולפאל די איליסימייפטו די טי פולול: טולפאמוק דייו די מואיקטלה קאלב׳אקייון אי באלדה טו קאנייאה קי קרן פלס: סי פארה קיימפלי טי איפסאנייאס קלן פלס קופטלאיק טופולור אה גיריפאפקייו אי גיריפאנקייו: דיקיירטו טו מורפאראק מוק אבידיגואראק אי טו פואיב׳לו קי אליגלאראן קון טי: אמוקטראמוק ה׳ טו מירקיד אי טו נןאלב׳אקײון דאלאק אה נוק: אולייריקי אב׳לארה איל דייו ה׳ קי אב׳לאלה
לאדינו
4
מי אסופלילאנן: אנביזאלי אריבילייאדלליס מיס קארילאס אי פיקאדוליס אנף טולנאלאן: איסקאפאמי די אומיזיילס דייו דייו די מי קאלבאסייון קאנטאלה מי לואינגח טי נוסטידאד: ה׳ מיס לאבייוס אנלילאס אי מי בוקה דימסייאלה טו לואול: קי פון אינבילונטאס סאקליציסייו ני דאדיבה אלסאסײון פון איפבילונטאק: קאקליפייוס די איל דייו איספיליטו קיבלאדו קול׳ קינלאדו אי מאזאדג דייו נון מינלספלייאה: אבונימאה קונטו בילונטאד אה ציון פלאגואלאק סילקאק די ילושלים: איסטונקיס איפבילונטאלאס סאקליפיקײוס די גוסטידאד אלקאקייון אי קימאדו איסטופסיס אלסאראן סובלי טו אלה טולוק: למ^צח אה איל איספולקאן קאלמו אה דוד קאפטאל: אטי קאל״אדורה לואול דיאיל דייו אין ציון אי אטי איס פאגאדה פלומיטה: אוליין אולאסייון אסטה טי טודה קלייאדולה בילפאן: פאלאבלאס די דיליטיס סי מאייולגאלון די מי מואיסטללס ליבילייוס מו ליס פידלונאלאס: ביין אבינטולאדו אל קי איסקוזיס אי אלייגאס קי מולי אץ מלס קולטיס אלטאלמוסאימוק קון ביין די טו קאזה סאפטו די טו פאלאסייו: טימו־ לידאדיס קון גלסטידאד ניס ליספונדילאס דייו די מלאיסטלה סאלבאסייון פיאוזייאה די טודלסקאנלס די טיילה אי מאל די לישאפיס: קונפוניץ מונטיס קון סו פואילסה סיניידו קון באלאגאנייאה: אזיין אקידאל סופידיס די מאליס סרפידיס די סוס אולאס אי לואידו די גיפטייוס: אי טימיילון מולאדוליק די קאנלס די טיס סינייאליס סאלידאס די מאנייאפה אי טאדלי אזיס קאנטאל: ביזיטאסטיס לה טיילה אי אניב׳לאסטיזלה מונגו לה אזיס איפליקיסיל פילאגו די איל דייו ייפו די אמאס קונפופי סו סיבילה קי אפסי לה קופפוניס: סוס ׳שללקיס אז אלטאל אז דיסינדילקון סיס באלייאדוס קון גוטאס לה דיזלייס סו אילמוייו ביפדידלאס: אינקולונאסטיס איל אפיץ די טו ביין אי טוס סינדיללס מטייאלאן ב׳יסייו. גוטייאלאן מולאדאס די דיזיילטו אי מזו די קואיסטאס סיפיילאן: ב׳יסטיילון פלאדוס לאס אוב׳יזאס אי נ׳אלייס איפבולב׳ילאן סיב׳ילה אאוב׳לאלאן טאמביין קאנטאלאן: ל£2^צח אה איל איספולסאן אה איזלס די קמזסאלמו: איפב׳ילופטאסטיס הי טו טיילה טולנאסטיס קאטיב׳ילײו די יטקב: פידלופאסטיס דיליטו די טו פואיב׳לל קלנ׳ליסמיס טודוס סיס פיקאדלס סיימפלי: אפאנייאסנרס טודה טו סאפייאה איזיסמיס טולנאל די איליסימיינטו די טו צולור: טולפאמלס דייו די מואיסטלה סאלב׳אסייון אי באלדה טו סאפייאה קי קון פלס: סי פאלה סיימפלי טי אינסאנײאס קון נלס סונטלאיס טו פולול אה גיליפאנסייו אי גיליפאנסייו: דיסיילטו טו טולפאלאס מלס אבידימאלאס אי טו פואיב׳לל סי אליגלאלאן קלן טי: אמלסטלאמלס ה' טו מילסיד אי טו סאלב׳אסייון דאלאס אה נלס: אולייליקי אב׳לאלה איל דייו ה' קי אב׳לאלה
לאדינו
5
פאס אנןו פואינ׳לו אי אקוק בואיפוק אי פון נװרנאראן אלוקורה: דינןײמװ קירקאפו אקוק טימיינטיק סו קאלב׳אקייון פור אפחיפטאר אופרה אין מואיקטרה טיירה: מירקיד אי ב׳ידראד פואימן איפקופטראדוק מקטידאד אי פאז סי ביזארון: ב׳ידראד די טיירה אירמוייקירה אי גוקטידאד די קיילוק קאטארה: טאמביץ ה׳ רארהאיל ניץ אי מואיקטרה טיירה דארה סואירמו״ו: מקנהדאד דילאנטרי איל אנדארה אי פורנה אקארירה סיס פאטאדאס: 271לדן אוראקייון אה איל מיקקינו קואנדו סי איפבולב׳י אי דילאפטרי ה׳ ב׳יירטיקו אוראסייון: ה׳אויי מיאוראקײון אי מי איקקלאמאקײון אטי ב׳ירפה: פון אינקוב׳ראק טוס פאקיק די מי אץ דייאה די אפגוסטייאה אמי אקוסטה אה מי טו אורי?ה אין דייאה קי טי ייאמארי די פריקה ריספונדימי: קי סי אטימארון אץ אומו מיס דייאס אי מיס גראיסוס קומו איל איפסיפדידירו סואירון איפקיפדידוק: צואי פירידו קומו לה יירב׳ה אי קיקוקי מי קור' קי מי אולב׳ידי די קומיר מי פאן: די בוז די מי קוקפירו סי אפינו מי גואיקו אה מי קארני: אקימי?י אה קיריקולו די דיזיירטו פואי קומו פאלקון די דיזיירמאק: אקינטינוב׳י אי פואי קומו פאשארו אבולחן קוב׳רי טיזאדו: טודו איל דײאה מי אריפודייארון מיק איפימיגוק מיק איפלוקיקידוק איפמי גורארון: אילקי קיפיזה קומו פאן קומיאימיק ביב׳ראזיק קון ייורו טיפפלי: פארה מודרי טו אירה אי טו סאנייאה קי מי אלסאסטים אי מי איגאקטיק: מיק דייאק קומו קולימברה אקוקטאדה אי ייו קומויירב׳ה מי קיקו: אי טו ה' פארה קיימפרי איקטאראק אי טו מימבראק״ון פארה גירינאנקי ו אי גיריפאפקייו: טו טי אליב׳אפטאראק אפייאדאראק ליון קי אורה פור איפיראקייארלה קי ב^יפו פלאזו: קי איפב׳ילונטארון טוק קיירב׳וק אקוק פיידראק אי אה קו פולב׳ו אגראקייאן: אי טימיראן גיפטיק די פומברי די ה' אי טודוק רייק די לה טיירה די טו אופרה: קי פראגואו ה׳ ליון פואי אפאריקידו קון קו אופרה: קאטו אאוראקייון די איל קולו איפו מיפוקפריק״ו אה קו אוראקייון: קייאה איקקריטו איקטו אה גיריפאפקייו פרוקטירו אי פואיב׳לו קרייאדו אלאב׳ארה אה ה׳: קי קאטודי אלטורה די קו קאנטידאד 0' די לוק קיילוק אה טיירה קאטו: פור אוייר גימידו די איפקארקילאדו פור קולטאר מיריקידוריק די מואירטי: פור ריקופטאר אין ציון פומברי די ה׳ אי קו לואור אין ירושלים: אין קיאיר אפאפייאדו פואיב׳לוק אה אופה אי רייפוק פור קירב׳יר אה ה׳: אפריאו אין לה קארירה מי פואירקה אקורטו מיק דיאק: דירי מי דייו פון מי טאזיק אין מיאטאד די מיק דיאק אין גירינאנקייו די גיריפאפקייוק טוק אפייוק: די אפטיק לה טיירה אקימינטאקטיק אי איגה די טוק מאפוק קיילוק: אילייוק קי דיפידריראן אי טו טי קוקטירנאק אי טודוק אילייוק קומו איל. פאנייו קי אינב׳יזיקיראן קומו איל ב׳יקטידו לוק
לאדינו
5
פאס אסו פואיג׳לו אי אסוס גיאיפיס אי הון טורפאראן אלרקורה: ריסײרטו סירקאנו אסוק נױמײמױק קו סאלב׳אסײון פור אפחינטאר אופרה אץ מואיקטרה טיירה: מירקיד אי ב׳ירראד פואילון איפקופטלאדוס טסטידאד קי פאז קי ביזארון: ב׳ידראד די טיירה אירמוייסירה אי גוקטידאד די קײלוק קאטאלה: טאמביץה׳ דארהאיל ביץ אי מואיקטרה טיירה דארה סואילמריו: גוקטידאד דילאנטרי איל אפדארה אי פורנה אקארירה קוק סאטאדאק: (ץ3לך[ אוראקייון אה איל מיקקינו קואנדו קי אינבולב׳י אי דילאנטרי ה׳ ב׳יירטיקו אוראקייון: ה׳ ארי מיאוראקייון אי מי איקקלאמאקייון אטי ב׳ירנה: פון אינקוב׳ראק טוק פאקיק די מי אין דייאה די אפגוקטייאה אמי אקוקטה אה מי טו אוריזה אין דייאה קי טי ייאמארי די פריקה ריקפונדימי: קי קי אטימארון אין אומו מיק דייאק אי מיק גואיקוק קומו איל אינקינדידירו פואירון אינקיפדידוק: $ואי פירידו קומו לה יירב׳ה אי קיקוקי מי קור' קי מי אולב׳ידי די קומיר מי פאן: די נח די מי קוקפירו קי אפטו מי גואיקו אה מי קארפי: אקימי׳זי אה קיריקולו די דיזיייטו פואי קומו פאלקון די דידירטאק: אקימרנוב׳י אי פואי קומו פא&ארו אבולאן קוב׳רי טיזאדו: טודו איל דייאה מי אריפודייאמן מיק אינימיגוק מיק איפלוקיקידוק איפמי גורארון: אילקי קיניזה קומו פאן קומיאימיק בט׳ראזיק קון ייללו טיפפלי: פארה מודרי טו אירה אי טו סאפייאה קי מי אלסאפטים אי מי איגאסטיק: מיס דייאק קומו קולומברה אקוקטאדה אי ייו קומויירב׳ה מי קיקי: אי טו ה׳ פארה קיימפיי איסטאראק אי טו מימנראקייון פארה גירינאפקי ו אי גיריפאפק״ו: טו טי אליב׳אפטאראק אפייאדאראק ציון קי אורה פור אינגראקייארלה קי 3;יפו פלאזו: קי איפנ׳ילונטארון טוק קיירב׳וק אסיס פיירראס אי אה קו פולב׳ו אגראסייאן: אי טימיראן גיפמיס די פומברי די ה׳ אי טודיס יייס די לה טיירה די טו אופרה: קי פראגואו ה, ציון פואי אפאריסידו קון סו אופרה: קאטו אאוראסײון די איל סולו איפו מיפוספליקייו אה קו אוראקייון: קייאה איקקריטו איקטו אה גיליפאפקייו פרוקטירו אי פואיב׳לו קרייאדו אלאב׳ארה אה ה׳: קי קאטודי אלטורה די קו קאנטידאד ה׳ די לוס סייליס אה טיירה קאטו: פור אריר גימידו די איפקארסילאדו פול סולטאר מיריסידוייס די מואירטי: פור ריקופטאר אץ ציון טמ3רי די ה׳ אי קו לואור אץ ירושלים: אין קיאיל אפאנייאדו פואינ׳לוק אה אופה אי ריינלס פור סירב׳יר אה ה': אפריאו אין לה קארירה מי פו א ירקה אקורטו מיס דיאס: דירי מי דייו טן מי טאזיס אץ מיאטאד די מיס דיאס אץ גירינאפקייו די גיריפאנסייוס טוס אפייוס: די אפנויס לה טיירה אסימיפטאסטיס אי איגה די טוק מאפוס קיילוק: אילייוס סי דיפידריראן אי טו מי סוקטירפאק אי טודיס אילייוק קומו איל פאפייו סי איפ3'יזיסיראן קומו איל נ׳יקטידו לוס
לאדינו
6