<!DOCTYPE corpora [
<!ELEMENT corpora (yes,no+)>
<!ATTLIST no right CDATA "">
<!ELEMENT yes (#PCDATA)>
<!ELEMENT no (#PCDATA)>
]>
<corpora>
    <yes>סליחוה נמנהג ק׳׳ק ספרדים יצ״</yes>

    <no right="ו">ו־</no>

    <yes> ---*0^0־--- נדפס פה ביינה שנת כת</yes>

    <no right="ר׳׳">ר</no>
    <yes>ה על ידי הצעיר יוסף יצהק אלשיך ה׳׳י ואשהו רבקה מנ״ה לזנרון אבדהם יצחק אלשיך ע</yes>
    <no right="׳׳">־</no>
    <yes>ה ויצחק יטקב אליהו ט</yes>
    <no right="׳׳">־</no>
    <yes> ה: סליחוה קון לאדינו</yes>
    <no right="ס">ק</no>
    <yes>י אי</yes>
    <no right="ס">ק</no>
    <yes>טאמפארון לה פרימה </yes>
    <no right="בˇ">ב</no>
    <yes>י</yes>
    <no right="ז">־</no>
    <yes> אין </yes>

    <no right="בˇ">ב</no>
    <yes>יינה אין אנייו 5625 אי</yes>

    <no right="טס">קנו</no>
    <yes>י לי</yes>

    <no right="בˇ">ב</no>
    <yes>רו איס אייאדו </yes>

    <no right="ס">ק</no>
    <yes>ולו אונדי</yes>

    <no right="ס">ק</no>
    <yes>י׳ יו</yes>

    <no right="ס">ק</no>
    <yes>ף יצחק אלשיך ה״י אין </yes>

    <no right="בˇ">ב</no>
    <yes>יינה. אי איל ריקא</yes>

    <no right="בˇ">ב</no>
    <yes>דו פו</yes>

    <no right="ר">ל</no>
    <yes> אייו אי</yes>

    <no right="ס">ק</no>
    <yes> אין</yes>

    <no right="פˇ">פ</no>
    <yes>א</yes>

    <no right="בˇ">ב</no>
    <yes>ור די גמילוה חסדים אמרי האזינה ה׳ בינה הגיגי הקשיבה לקול שוטי מלני ואלהי ני אליך אהפלל</yes>

    <no right=":">ן</no>

    <yes> יזנור ואל ישנך מלברך נרנוה התורה </yes>

    <no right="כד">בר</no>
    <yes>י לומר סליחוה נרטה רבינו בטל הטורים </yes>

    <no right="ו׳׳">ר</no>
    <yes>ל שפסק שלא יקרא פסו</yes>

    <no right="ק">ס</no>
    <yes>י</yes>

    <no right="ם">ש</no>
    <yes> קורם ברנה ההורה אף טל פי שאומרים דרך החנונים. ואשר בא בסוד ה׳ י</yes>

    <no right="כו">מ</no>
    <yes>ין לברך בטה ההיא נל סדר הברנוה יטן שאינו ראוי להפסיק </yes>
    <no right="ב">נ</no>
    <yes>י</yes>


    <no right="נ">ג</no>
    <yes>יהם כי קשר ויהוד אחד לכולם מההלה נטילה ידים טד ברנוה ההורה ננודט ליודטי חן גם צריך ליזהר לומר נל סדר הקון חצוה נפי מה שהובא בספר שטרי צ</yes>

    <no right="ןיו">ק</no>
    <yes> ני הוא טיקר גדול לבנוה ולההאבל טל חרבן ביה מקדשינו וישב יחף טל הארץ ויהחיל טל נהרוה בבל ונו׳ ננהוב שם: מיס די</yes>

    <no right="גˇ">ג</no>
    <yes>א</yes>

    <no right="ס">ק</no>
    <yes> אי</yes>

    <no right="ס">ק</no>
    <yes>ק</yes>
    <no right="וגˇ">גל</no>
    <yes>ה ה׳ אינ</yes>
    <no right="טיי">נרי</no>
    <yes>נדי מי א</yes>

    <no right="בˇ">ב</no>
    <yes>לה איסקו</yes>

    <no right="גˇ">ג</no>
    <yes>ה אה </yes>

    <no right="ב">נ</no>
    <yes>וס </yes>

    <no right="ד">ר</no>
    <yes>י מי איסקלאמא</yes>

    <no right="ס">ק</no>
    <yes>ייו</yes>

    <no right="ן">;</no>
    <yes> מי </yes>

    <no right="רי">מ</no>
    <yes>י אי מי דייו קי א</yes>

    <no right="ט">בר</no>
    <yes>י אגו אוראסייון: מימ</yes>

    <no right="ב">נ</no>
    <yes>רארה אי </yes>

    <no right="נו">מ</no>
    <yes>ן אול</yes>
    <no right="בˇ">ב</no>
    <yes>ידארה די בינ</yes>
    <no right="דיזי">ריד</no>
    <yes>ר לאס בינ</yes>
    <no right="ד">ל־</no>
    <yes>יסײוניס די לה ליי פארה דיזיר סליחוה סי</yes>
    <no right="ג">ב</no>
    <yes>ון ס</yes>
    <no right="בˇ">ב</no>
    <yes>רה די רב</yes>
    <no right="ינ">ט</no>
    <yes>ו בעל ה</yes>
    <no right="ט">נו</no>
    <yes>ורי</yes>
    <no right="ם">ס</no>
    <yes>ז״ל איל קואל קורטו פור</yes>
    <no right="ר">ד</no>
    <yes>ין די </yes>
    <no right="נו">מ</no>
    <yes>ן די</yes>
    <no right="זי">ד</no>
    <yes>ר אי מילדאר פסוקים אנ</yes>
    <no right="ט">נו</no>
    <yes>יס די בינדי</yes>
    <no right="ס">ק</no>
    <yes>ײוניס די לה ליי אא</yes>
    <no right="ןו">ץ</no>
    <yes> קי לוס דיזין פור רוגא</yes>
    <no right="ט">נו</no>
    <yes>י</yes>
    <no right="בˇ">ב</no>
    <yes>ה: אי איל קי </yes>
    <no right="בˇ">ב</no>
    <yes>ינו אין סיקרי</yes>
    <no right="ט">נו</no>
    <yes>ו די ה׳ </yes>
    <no right="טי">נר</no>
    <yes>נגה לה אינ</yes>
    <no right="ט">נו</no>
    <yes>יסייון די בינדיזיר אין איס</yes>
    <no right="ט">נו</no>
    <yes>ה אורה טודו איל אורד</yes>
    <no right="ין">ץ</no>
    <yes> די בינדיסייוניס סײנדו קי נין איס פיר-טיניסיין פור איס</yes>
    <no right="ט">נו</no>
    <yes>א</yes>
    <no right="זˇ">ז</no>
    <yes>אר אינ</yes>
    <no right="ט">נו</no>
    <yes>רי אייאס פו</yes>
    <no right="ר">נ</no>
    <yes>קי א</yes>
    <no right="ט">נו</no>
    <yes>א</yes>
    <no right="מי">נר</no>
    <yes>ינ</yes>
    <no right="ט">נו</no>
    <yes>ו אי אאונאמיינ</yes>
</corpora>